MB-35424: Unnecessary fields will now be truncated within FTS
Exception: score which is of type int

Requires: http://review.couchbase.org/112876

Change-Id: I62413b4eca2254f72c91b7f990ada4444ad2273a
Reviewed-on: http://review.couchbase.org/112877
Reviewed-by: Sreekanth Sivasankaran <sreekanth.sivasankaran@couchbase.com>
Tested-by: Abhinav Dangeti <abhinav@couchbase.com>
Well-Formed: Build Bot <build@couchbase.com>