Fix test failures due to missing APIs for interface
```
flex/whitebox/server.go:72:9: cannot use this (variable of type *Request) as type execution.Output in return statement:
	*Request does not implement execution.Output (missing LogLevel method)
flex/whitebox/server.go:145:23: cannot use req (variable of type *Request) as type server.Request in argument to s.ServiceRequest:
	*Request does not implement server.Request (missing Alive method)
flex/whitebox/server.go:72:9: cannot use this (variable of type *Request) as type execution.Output in return statement:
	*Request does not implement execution.Output (missing Loga method)
flex/whitebox/server.go:153:23: cannot use req (variable of type *Request) as type server.Request in argument to s.ServiceRequest:
	*Request does not implement server.Request (missing Loga method)
```

Change-Id: Icc283f31a0a14c71aa2bbf3c021efbac60ff6084
Reviewed-on: https://review.couchbase.org/c/n1fty/+/187260
Well-Formed: Build Bot <build@couchbase.com>
Tested-by: Abhi Dangeti <abhinav@couchbase.com>
Reviewed-by: Abhi Dangeti <abhinav@couchbase.com>